### ISSUE TITLE
Allow use of environment variables in config file

### ISSUE THREAD

**Issue by SvenMarcus** [SvenMarcus/hpc-rocket#25]
It may be convenient to use environment variables in the configuration file, for example when providing a password through a variable inside a CI pipeline.

Proposed syntax:
```yaml
host: myhost
user: myuser
password: $mypassword
```
