### ISSUE TITLE
Simplify batch configuration

### ISSUE THREAD

**Issue by SvenMarcus** [SvenMarcus/hpc-rocket#48]
If the slurm job file is not present on the remote machine already users need to specify it in the `copy` section and then again with the `sbatch` key of their configuration file.

This is a bit redundant and can be simplified by using the same structure as the copy section:
```yaml
sbatch:
  from: local_file.sh
  to: remote_file.sh
```

If the remote file is already present, we can still fall back to the current approach:
```yaml
sbatch: remote_file.sh
```
