### ISSUE TITLE
SlurmError: sbatch slurm.job

### ISSUE THREAD

**Issue by MartinGrignard** [SvenMarcus/hpc-rocket#51]
Hi :wave:

I'm currently trying to run HPC-rocket to submit a job from my local machine (before integrating it in a GitLab CI/CD pipeline).
I created a simple `slurm.job` that only prints the hostname to check if the job runs properly.

Here is my configuration:
```yaml
host: ...
user: ...
private_keyfile: ...

copy:
  - from: slurm.job
    to: slurm.job
    overwrite: true

clean:
  - slurm.job
  - slurm-hpc-rocket.log

sbatch: slurm.job
```
When I run the following command:
```
hpc-rocket launch --watch config.yml
```
I get the following output:
```
ℹ Copying files...
✔  Done
❌ SlurmError: sbatch slurm.job
[==  ]
```
Since there is no additional logs, and the job runs when I submit it manually on the cluster, do you have any idea of what could be the problem here?

Thanks!
